<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Edit Page') ?></h3>
            </div>
            <div class="panel-body">
                <p>Hi</p>
                <p><a class="btn btn-success pull-right" href="" target=""><?php echo $this->translate('Hello') ?></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Edit Page') ?></h3>
            </div>
            <div class="panel-body">
                <p>Hi</p>
                <p><a class="btn btn-success pull-right" href="" target=""><?php echo $this->translate('Hello') ?></a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Edit Page') ?></h3>
            </div>
            <div class="panel-body">
                <p>Hi</p>
                <p><a class="btn btn-success pull-right" href="" target=""><?php echo $this->translate('Hello') ?></a></p>
            </div>
        </div>
    </div>
</div>
